### ISSUE TITLE
menu icon dissapears on click

### ISSUE THREAD

**Issue by marcusellison** [venturemark/webclient#310] opened 2021-05-04 20:55 UTC
**Problem:**

Clicking on a sidebar item causes the icon-menu that is present on hover to disappear.

**To recreate:**

1. Click on the venture sidebaritem
2. move cursor to hover over timeline sidebaritem
3. click on timeline sidebaritem

![](http://g.recordit.co/lBRzj0pZqB.gif)

**Expected behavior:**

The menu item is still visible after clicking on the sidebar item.

**Comment by tfussell** [comment] 2021-05-28 11:58
This is likely a duplicate of https://github.com/venturemark/webclient/issues/273 I will confirm before closing though.

**Closed** 2021-06-16 20:54 UTC
Labels: priority/low
